# General settings
title: "HackGPT Toyko"
description: "ChatGPTを活用したシステムを作ろう！オリジナルのAIペットを作るワークショップ付き"
keywords: "ChatGPT, HackGPT, 東京, ハッカソン, AI, アプリケーション, 学生"
author: "HackGPT Tokyo"
banner: "/images/opg.png"

# People
people:
  - name: "スコット アトム"
    affiliation: "名古屋大学大学院 博士1年"
    twitter: "https://twitter.com/AtomJamesScott"
    github: "https://github.com/atomscott"
    website: "https://atomscott.me"
    image: "atom_scott_heads.png"
    image_hover: "atom_scott_tails.png"
    bio: "1997年（イギリス・ロンドン）生まれ。筑波大学で情報技術を学びながら蹴球部のデータ分析担当を務めた。その後、筑波大学大学院でスポーツ×AIに関する研究に従事し、名古屋大学大学院情報学研究科へ進学。シミュレーションやコンピュータビジョンの国際会議において複数回発表。2022年度未踏IT人材発掘・育成事業に採択。現在は映像認識やシミュレーション技術を研究し、人間の動きを計算可能にすることを目指す。"
  - name: "山形 昌弘"
    affiliation: "東京大学大学院 修士2年"
    image: "masahiro_yamagata_heads.JPG"
    bio: "Here you can add more information about the person 1."
  - name: "皆川 達也"
    affiliation: "筑波大学大学院 修士2年"
    image: "tatsuya_minagawa.jpg"
    bio: "Here you can add more information about the person 1."
  - name: "岡野 木沙乃"
    affiliation: "㈱Cyberagent Capital ジュニア・アソシエート"
    image: "kisano_okano.jpg"
    bio: "Here you can add more information about the person 1."
